# Generated by Django 4.0.2 on 2022-02-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('A', 'Album'), ('S', 'Single'), ('C', 'Compilation'), ('AO', 'Appears_on')], max_length=10)),
                ('release_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('collaborative', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='UsersPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('O', 'Owner'), ('C', 'Collaborator')], default='O', max_length=1)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to='music_app.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to='music_app.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['display_name'], name='music_app_u_display_4a1854_idx'),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_app.album'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(related_name='artists', through='music_app.ArtistTrack', to='music_app.Artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=models.ManyToManyField(related_name='tracks', through='music_app.PlaylistTrack', to='music_app.Playlist'),
        ),
        migrations.AddField(
            model_name='track',
            name='users',
            field=models.ManyToManyField(related_name='tracks', through='music_app.PlaylistTrack', to='music_app.User'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_track', to='music_app.playlist'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_track', to='music_app.track'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_track', to='music_app.user'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='users',
            field=models.ManyToManyField(related_name='playlists', through='music_app.UsersPlaylists', to='music_app.User'),
        ),
        migrations.AddField(
            model_name='artisttrack',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_track', to='music_app.artist'),
        ),
        migrations.AddField(
            model_name='artisttrack',
            name='artist_feat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_feat', to='music_app.artist'),
        ),
        migrations.AddField(
            model_name='artisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_track', to='music_app.track'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='music_app_a_name_33d04f_idx'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_app.artist'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['name'], name='music_app_t_name_7d4dae_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['name'], name='music_app_p_name_6a7d33_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['name'], name='music_app_a_name_54c5e2_idx'),
        ),
    ]
