# Generated by Django 4.0.2 on 2022-02-10 09:52

from re import I
from django.db import migrations
from src.initial_db_data import Spotify


def initial_db_data(apps, schema_editor):
    


    '''
    User = apps.get_model('music_app', 'User')
    user = User.objects.create(id="test1", display_name="test_name1")
    

    Playlist = apps.get_model('music_app', 'Playlist')
    p= Playlist.objects.create(id= "2ZUUYxDkNiYwrcMhMLUgJl", name="Mis pistas de Shazam", public="True")
    
    UsersPlaylists = apps.get_model('music_app', 'UsersPlaylists')
    UsersPlaylists.objects.create(user=user, playlist=p)


    user = User.objects.create(id="test2", display_name="test_name2")  
    UsersPlaylists.objects.create(user=user, playlist=p, user_type='C')
 '''



class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_db_data),
    ]
    
