# Generated by Django 4.0.2 on 2022-02-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_usersplaylists_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersplaylists',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userplaylist', to='music_app.playlist'),
        ),
        migrations.AlterField(
            model_name='usersplaylists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userplaylist', to='music_app.user'),
        ),
    ]
